# Generated by Django 5.1.1 on 2026-05-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cab_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='cab_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cabs.cabtype'),
        ),
    ]
