# Generated by Django 5.1.1 on 2026-05-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='places.category'),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.touristplace'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.touristplace'),
        ),
        migrations.AddIndex(
            model_name='touristplace',
            index=models.Index(fields=['city', 'country'], name='tourist_pla_city_ce7c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='touristplace',
            index=models.Index(fields=['category'], name='tourist_pla_categor_5fcb41_idx'),
        ),
        migrations.AddIndex(
            model_name='touristplace',
            index=models.Index(fields=['status'], name='tourist_pla_status_f9a981_idx'),
        ),
        migrations.AddIndex(
            model_name='touristplace',
            index=models.Index(fields=['latitude', 'longitude'], name='tourist_pla_latitud_2483ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'place')},
        ),
    ]
