# Generated by Django 5.1.1 on 2026-05-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['visitor', 'status'], name='bookings_visitor_8c7e36_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['place', 'visit_date'], name='bookings_place_i_021f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='bookings_booking_ea21fb_idx'),
        ),
    ]
