# Generated by Django 5.1.1 on 2026-05-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='placeanalytics',
            unique_together={('place', 'date')},
        ),
        migrations.AddIndex(
            model_name='visitoractivity',
            index=models.Index(fields=['user', 'action'], name='visitor_act_user_id_beb6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoractivity',
            index=models.Index(fields=['action', 'created_at'], name='visitor_act_action_c77577_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoractivity',
            index=models.Index(fields=['resource_type', 'resource_id'], name='visitor_act_resourc_9a6211_idx'),
        ),
    ]
