# Generated by Django 5.1.1 on 2026-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected'), ('cab_confirmed', 'Cab Booking Confirmed'), ('cab_cancelled', 'Cab Booking Cancelled'), ('system', 'System Notification'), ('promo', 'Promotion')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
